name: Discord Issue Comment Notify

on:
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message
        run: |
          curl -v -X POST \
          -H "Content-Type: application/json" \
          -d '{"content":"debug message from github"}' \
          ${{ secrets.DISCORD_WEBHOOK }}}
